version: '3'

services:
  frontend:
    build: 
      context: '.'
      args:
        SAME_ORIGIN: ${SAME_ORIGIN-}
        VITE_SAME_ORIGIN: ${SAME_ORIGIN-}
    labels:
      shipyard.route: '/'
    ports:
      - '3000:3000'
    env_file:
      - .env
  # backend:
  #   build: .
  #   ports:
  #     - '3001:3001'
  #   env_file:
  #     - .env
  #   volumes:
  #     - './data:/data'


