version: '3'

services:
  frontend:
    build:
      context: '.'
      args:
        SAME_ORIGIN: ${SAME_ORIGIN-}
        VITE_SAME_ORIGIN: ${SAME_ORIGIN-}
    labels:
      shipyard.route: '/'
    environment:
        SAME_ORIGIN: ${SAME_ORIGIN-}
        VITE_SAME_ORIGIN: ${SAME_ORIGIN-}
        SHIPYARD_DOMAIN_FRONTEND: ${SHIPYARD_DOMAIN_FRONTEND-}
    ports:
      - '3000:3000'
    env_file:
      - .env

  # backend:
  #   build:
  #     context: '.'
  #     args:
  #       SAME_ORIGIN: ${SAME_ORIGIN-}
  #       VITE_SAME_ORIGIN: ${SAME_ORIGIN-}
  #   labels:
  #     shipyard.route: '/'
  #   environment:
  #       SAME_ORIGIN: ${SAME_ORIGIN-}
  #       VITE_SAME_ORIGIN: ${SAME_ORIGIN-}
  #       SHIPYARD_DOMAIN_FRONTEND: ${SHIPYARD_DOMAIN_FRONTEND-}
  #   ports:
  #     - '3001:3001'
  #   env_file:
  #     - .env
